version: "3.9"
services:
  mysql:
    container_name: mysqldatabase
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cinemaProject
    volumes:
      - mysql_data:/var/lib/mysqldatabase
    restart: always

  # frontend:
  #   container_name: cinema-frontend
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://localhost:8080
  #     - VITE_GOOGLE_CLIENT_ID=798741108575-snc0su2r1cek5egop88vqs3rq5oda3j2.apps.googleusercontent.com
  #   restart: always

  backend:
    container_name: cinema-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cinemaProject
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always

volumes:
  mysql_data:
